## CHANGE this to the name of your plugin.
name: Magic8Ball

## CHANGE this to your username.
author: xMoonGames

## CHANGE this to a meaningful but short description of your plugin.
description: The Magic 8 Ball addon brings the classic fortune-telling toy into Minecraft

## CHANGE this to the path of the class that extends JavaPlugin.
main: com.xmooncorp.magic8ball.Magic8Ball

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/xMoonGames/Magic-8-Ball

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.20

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun